import { useState } from "react";

const scholarships = [
  { id:"tech", name:"Technology Excellence Scholarship", school:"Đại học Công nghệ Mẫu", country:"Việt Nam", score:88, funding:"75% học phí", gpa:"Từ 3.2 / 4.0", ielts:"IELTS 6.5", gap:"Cần nâng IELTS thêm 0.5", deadline:"31 tháng 01, 2027", reminder:"Hoàn tất hồ sơ trước 24 tháng 01", tag:"Phù hợp nhất" },
  { id:"global", name:"Global Futures Scholarship", school:"International Sample University", country:"Úc", score:71, funding:"Toàn phần", gpa:"Từ 3.6 / 4.0", ielts:"IELTS 7.0", gap:"Thiếu GPA 0.1 và IELTS 1.0", deadline:"15 tháng 12, 2026", reminder:"Hoàn tất hồ sơ trước 08 tháng 12", tag:"Mục tiêu phát triển" },
];
const gaps=[["GPA","3.5 / 4.0","Đạt","Vượt yêu cầu của lựa chọn ưu tiên 0.3 điểm."],["IELTS","6.0","Cần bổ sung","Cần đạt 6.5 trước khi nộp hồ sơ ưu tiên."],["Hoạt động","CLB Công nghệ","Cần củng cố","Bổ sung một dự án có kết quả đo lường được."],["Chứng chỉ","Còn hạn đến 06/2027","Đạt","Chứng chỉ hiện còn hiệu lực cho kỳ nhập học 2027."]];
const tasks=[["Đăng ký và hoàn thành IELTS 6.5","30 tháng 11, 2026"],["Hoàn thiện CV, bảng điểm và portfolio","20 tháng 12, 2026"],["Xin hai thư giới thiệu","10 tháng 01, 2027"],["Rà soát hồ sơ và nộp đơn","24 tháng 01, 2027"]];
const flow=["Profile","Agent Analysis","Scholarship Matches","Gap Analysis","Application Plan"];
const steps=["Đã phân tích GPA, IELTS và mục tiêu học tập","Đã tìm cơ hội theo ngành CNTT và kỳ 2027","Đã kiểm tra yêu cầu tuyển sinh và funding","Đã phát hiện khoảng thiếu cần ưu tiên"];

export function App(){
 const [selectedId,setSelectedId]=useState(null),[details,setDetails]=useState(null),[compare,setCompare]=useState(false),[done,setDone]=useState([false,false,false,false]),[input,setInput]=useState(""),[messages,setMessages]=useState([["agent","Mình đã phân tích hồ sơ và tìm được hai cơ hội phù hợp. Lựa chọn đầu tiên có mức phù hợp cao nhất, với khoảng thiếu chính là IELTS."]]);
 const selected=scholarships.find(x=>x.id===selectedId);
 const createPlan=id=>{setSelectedId(id);setTimeout(()=>document.querySelector("#application-plan")?.scrollIntoView({behavior:"smooth",block:"start"}),0)};
 const submit=e=>{e.preventDefault();const text=input.trim();if(!text)return;const answer=text.toLowerCase().includes("ielts")?"Khoảng thiếu quan trọng nhất hiện tại là IELTS: bạn cần tăng từ 6.0 lên tối thiểu 6.5 trước cuối tháng 11 năm 2026.":"Mình sẽ dùng GPA, chứng chỉ, hoạt động, ngành học, kỳ nhập học và nhu cầu funding để xếp hạng các lựa chọn.";setMessages(m=>[...m,["user",text],["agent",answer]]);setInput("")};
 return <main className="experience"><section className="frame">
  <header className="topbar"><button className="brand"><b>S</b><span>ScholarAI</span></button><nav><button className="active">Tổng quan</button><button>Hồ sơ</button><button>Kế hoạch</button></nav><span className="person"><i>KL</i>Khánh Linh</span></header>
  <section className="hero"><div className="hero-copy"><p className="eyebrow">Scholarship planning agent</p><h1>Biến hồ sơ thành lộ trình nộp học bổng.</h1><p>Nhận phân tích rõ ràng, lựa chọn phù hợp và kế hoạch theo đúng deadline.</p><button onClick={()=>document.querySelector("#matches")?.scrollIntoView({behavior:"smooth"})}>Xem cơ hội phù hợp</button></div><div className="art" role="img" aria-label="Minh họa hành trình chuẩn bị học bổng"/></section>
  <section className="flow">{flow.map((x,i)=><div className={i<4?"flow-step complete":"flow-step"} key={x}><span>{i+1}</span><b>{x}</b></div>)}</section>
  <section className="overview"><article className="panel"><div className="title"><div><p className="eyebrow">Profile</p><h2>Hồ sơ của Khánh Linh</h2></div><button>Chỉnh sửa</button></div><p className="muted">Thạc sĩ Công nghệ thông tin · Kỳ nhập học 2027</p><div className="stats"><div><b>3.5</b><small>GPA / 4.0</small></div><div><b>6.0</b><small>IELTS</small></div><div><b>01</b><small>Hoạt động</small></div></div><p className="muted">Nền tảng học thuật tốt. Tập trung cải thiện IELTS và minh chứng dự án công nghệ.</p></article>
  <section className="panel agent"><div className="title"><div><p className="eyebrow">Agent analysis</p><h2>Agent đã làm gì?</h2></div><span className="badge good">Đã cập nhật</span></div><div className="agent-steps">{steps.map((x,i)=><div key={x}><span>{i+1}</span><p>{x}</p><b>✓</b></div>)}</div><form onSubmit={submit}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Hỏi về điều kiện hoặc kế hoạch của bạn..."/><button>Gửi</button></form><div className="messages">{messages.slice(-3).map(([r,x],i)=><p className={r} key={i}>{x}</p>)}</div></section></section>
  <section className="section" id="matches"><div className="heading"><div><p className="eyebrow">Scholarship matches</p><h2>Cơ hội phù hợp với hồ sơ</h2><p>Được xếp hạng theo mức phù hợp hiện tại và khả năng hoàn thành trước hạn.</p></div><button className="compare" onClick={()=>setCompare(!compare)}>{compare?"Đang so sánh":"So sánh lựa chọn"}</button></div><div className="cards">{scholarships.map(s=><article className={details===s.id?"card expanded":"card"} key={s.id}><div className="card-top"><span><b>{s.score}</b>/100 phù hợp</span><span className="badge">{s.tag}</span></div><h3>{s.name}</h3><p>{s.school} · {s.country}</p><strong>{s.funding}</strong><div className="requirements"><p>GPA<b>{s.gpa}</b></p><p>IELTS<b>{s.ielts}</b></p></div><div className="gap"><b>Khoảng thiếu</b><span>{s.gap}</span></div><p className="deadline"><span>Deadline</span><b>{s.deadline}</b></p>{details===s.id&&<p className="detail">{s.reminder}. Ưu tiên các điều kiện bắt buộc trước khi chuẩn bị bài luận.</p>}<div className="actions"><button onClick={()=>setDetails(details===s.id?null:s.id)}>Xem chi tiết</button><button onClick={()=>setCompare(true)}>So sánh</button><button className="primary" onClick={()=>createPlan(s.id)}>Tạo kế hoạch</button></div></article>)}</div></section>
  <section className="section"><div className="heading"><div><p className="eyebrow">Gap analysis</p><h2>Bạn còn thiếu gì?</h2><p>Tập trung vào những hạng mục tác động trực tiếp đến khả năng đủ điều kiện.</p></div></div><div className="gap-grid">{gaps.map(([a,b,c,d])=><article className={c==="Đạt"?"gap-card good-card":"gap-card"} key={a}><p>{a}</p><strong>{b}</strong><span className={c==="Đạt"?"badge good":"badge warn"}>{c}</span><small>{d}</small></article>)}</div></section>
  {selected&&<section className="section plan" id="application-plan"><div className="heading"><div><p className="eyebrow">Application plan</p><h2>Kế hoạch cho {selected.name}</h2><p>{selected.school} · Deadline {selected.deadline}</p></div><div className="reminder"><span>Nhắc hạn</span><b>{selected.reminder}</b></div></div><div className="plan-grid"><article className="panel"><div className="progress"><b>{done.filter(Boolean).length}/4</b><span> công việc hoàn thành</span><i><em style={{width:`${done.filter(Boolean).length*25}%`}}/></i></div>{tasks.map(([t,d],i)=><label className="task" key={t}><input type="checkbox" checked={done[i]} onChange={()=>setDone(x=>x.map((v,j)=>i===j?!v:v))}/><span><b>{t}</b><small>Hoàn thành trước {d}</small></span><em>{done[i]?"Hoàn thành":i===0?"Ưu tiên cao":"Chưa bắt đầu"}</em></label>)}</article><aside className="timeline"><p className="eyebrow">Timeline</p>{tasks.map(([t,d],i)=><div key={t}><span>{i+1}</span><p><b>{d}</b><small>{t}</small></p></div>)}</aside></div></section>}
 </section></main>
}
